# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3aa9790477fa72b562d833d3c7bd0108"
name = "germaine-joseph-clone-dev"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_customers,write_customers,read_orders,write_orders,read_metaobjects,write_metaobjects,write_metaobject_definitions"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
