import type { MtmOptionSet } from '@/types/trouserOptions';

export const blazerOptionSet: MtmOptionSet = {
  id: 'blazer-core-v1',
  handle: 'blazer-core-v1',
  title: 'Blazer Core v1',
  category: 'blazer',
  version: 'v1',
  options: [
    {
      key: 'fit',
      label: 'Blazer Fit',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 10,
      section: 'design',
      choices: [
        { value: 'slim', label: 'Slim', priceDelta: 0 },
        { value: 'tailored', label: 'Tailored', priceDelta: 0 },
        { value: 'classic', label: 'Classic', priceDelta: 0 },
      ],
    },
    {
      key: 'buttoning',
      label: 'Buttoning',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 20,
      section: 'design',
      choices: [
        { value: 'single_two', label: 'Single Breasted (2)', priceDelta: 0 },
        { value: 'single_three', label: 'Single Breasted (3)', priceDelta: 1200 },
        { value: 'double_six', label: 'Double Breasted (6)', priceDelta: 2600 },
      ],
    },
    {
      key: 'lapel_type',
      label: 'Lapel Type',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 30,
      section: 'design',
      choices: [
        { value: 'notch', label: 'Notch', priceDelta: 0 },
        { value: 'peak', label: 'Peak', priceDelta: 1800 },
      ],
    },
    {
      key: 'pocket_style',
      label: 'Pocket Style',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 40,
      section: 'pockets',
      choices: [
        { value: 'patch', label: 'Patch', priceDelta: 0 },
        { value: 'flap', label: 'Flap', priceDelta: 0 },
        { value: 'jetted', label: 'Jetted', priceDelta: 900 },
      ],
    },
    {
      key: 'vent',
      label: 'Back Vent',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 50,
      section: 'construction',
      choices: [
        { value: 'none', label: 'No Vent', priceDelta: 0 },
        { value: 'single', label: 'Single Vent', priceDelta: 0 },
        { value: 'double', label: 'Double Vent', priceDelta: 1200 },
      ],
    },
    {
      key: 'lining',
      label: 'Lining',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 60,
      section: 'construction',
      choices: [
        { value: 'full', label: 'Full', priceDelta: 2000 },
        { value: 'half', label: 'Half', priceDelta: 900 },
        { value: 'unlined', label: 'Unlined', priceDelta: 0 },
      ],
    },
    {
      key: 'button_finish',
      label: 'Button Finish',
      type: 'select',
      uiHint: 'dropdown',
      required: false,
      sortOrder: 70,
      section: 'finish',
      choices: [
        { value: 'standard', label: 'Standard', priceDelta: 0 },
        { value: 'horn', label: 'Horn', priceDelta: 1000 },
        { value: 'metal', label: 'Metal Crest', priceDelta: 1800 },
      ],
    },
  ],
};
