import type { MtmOptionSet } from '@/types/trouserOptions';

export const overcoatOptionSet: MtmOptionSet = {
  id: 'overcoat-core-v1',
  handle: 'overcoat-core-v1',
  title: 'Overcoat Core v1',
  category: 'overcoat',
  version: 'v1',
  options: [
    {
      key: 'silhouette',
      label: 'Silhouette',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 10,
      section: 'design',
      choices: [
        { value: 'tailored', label: 'Tailored', priceDelta: 0 },
        { value: 'relaxed', label: 'Relaxed', priceDelta: 0 },
      ],
    },
    {
      key: 'length',
      label: 'Length',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 20,
      section: 'design',
      choices: [
        { value: 'short', label: 'Short', priceDelta: 0 },
        { value: 'knee', label: 'Knee', priceDelta: 0 },
        { value: 'long', label: 'Long', priceDelta: 1600 },
      ],
    },
    {
      key: 'closure',
      label: 'Closure',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 30,
      section: 'construction',
      choices: [
        { value: 'single_breasted', label: 'Single Breasted', priceDelta: 0 },
        { value: 'double_breasted', label: 'Double Breasted', priceDelta: 2200 },
      ],
    },
    {
      key: 'lapel',
      label: 'Lapel',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 40,
      section: 'design',
      choices: [
        { value: 'notch', label: 'Notch', priceDelta: 0 },
        { value: 'peak', label: 'Peak', priceDelta: 1400 },
        { value: 'shawl', label: 'Shawl', priceDelta: 1800 },
      ],
    },
    {
      key: 'lining',
      label: 'Lining Weight',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 50,
      section: 'construction',
      choices: [
        { value: 'light', label: 'Light', priceDelta: 0 },
        { value: 'quilted', label: 'Quilted', priceDelta: 1800 },
        { value: 'full_winter', label: 'Full Winter', priceDelta: 2600 },
      ],
    },
    {
      key: 'belt',
      label: 'Belt',
      type: 'radio',
      uiHint: 'buttons',
      required: false,
      sortOrder: 60,
      section: 'details',
      choices: [
        { value: 'none', label: 'No Belt', priceDelta: 0 },
        { value: 'half_belt', label: 'Half Belt', priceDelta: 900 },
        { value: 'full_belt', label: 'Full Belt', priceDelta: 1200 },
      ],
    },
    {
      key: 'button_finish',
      label: 'Button Finish',
      type: 'select',
      uiHint: 'dropdown',
      required: false,
      sortOrder: 70,
      section: 'finish',
      choices: [
        { value: 'standard', label: 'Standard', priceDelta: 0 },
        { value: 'horn', label: 'Horn', priceDelta: 1200 },
        { value: 'leather', label: 'Leather Wrapped', priceDelta: 1800 },
      ],
    },
  ],
};
