import type { MtmOptionSet } from '@/types/trouserOptions';

export const shirtOptionSet: MtmOptionSet = {
  id: 'shirt-core-v1',
  handle: 'shirt-core-v1',
  title: 'Shirt Core v1',
  category: 'shirt',
  version: 'v1',
  options: [
    {
      key: 'fit',
      label: 'Shirt Fit',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 10,
      section: 'design',
      choices: [
        { value: 'slim', label: 'Slim', priceDelta: 0 },
        { value: 'tailored', label: 'Tailored', priceDelta: 0 },
        { value: 'classic', label: 'Classic', priceDelta: 0 },
      ],
    },
    {
      key: 'collar',
      label: 'Collar',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 20,
      section: 'design',
      choices: [
        { value: 'spread', label: 'Spread', priceDelta: 0 },
        { value: 'cutaway', label: 'Cutaway', priceDelta: 600 },
        { value: 'button_down', label: 'Button Down', priceDelta: 0 },
        { value: 'mandarin', label: 'Mandarin', priceDelta: 800 },
      ],
    },
    {
      key: 'cuff',
      label: 'Cuff',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 30,
      section: 'construction',
      choices: [
        { value: 'single_rounded', label: 'Single Rounded', priceDelta: 0 },
        { value: 'single_square', label: 'Single Square', priceDelta: 0 },
        { value: 'double_french', label: 'Double French', priceDelta: 1000 },
      ],
    },
    {
      key: 'placket',
      label: 'Front Placket',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 40,
      section: 'construction',
      choices: [
        { value: 'standard', label: 'Standard', priceDelta: 0 },
        { value: 'hidden', label: 'Hidden', priceDelta: 600 },
        { value: 'covered', label: 'Covered', priceDelta: 900 },
      ],
    },
    {
      key: 'front_pocket',
      label: 'Front Pocket',
      type: 'radio',
      uiHint: 'buttons',
      required: false,
      sortOrder: 50,
      section: 'pockets',
      choices: [
        { value: 'none', label: 'No Pocket', priceDelta: 0 },
        { value: 'single', label: 'Single Pocket', priceDelta: 0 },
        { value: 'double', label: 'Double Pocket', priceDelta: 700 },
      ],
    },
    {
      key: 'hem',
      label: 'Hem Style',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 60,
      section: 'finish',
      choices: [
        { value: 'rounded', label: 'Rounded', priceDelta: 0 },
        { value: 'straight', label: 'Straight', priceDelta: 0 },
      ],
    },
    {
      key: 'monogram',
      label: 'Monogram',
      type: 'select',
      uiHint: 'dropdown',
      required: false,
      sortOrder: 70,
      section: 'finish',
      choices: [
        { value: 'none', label: 'None', priceDelta: 0 },
        { value: 'cuff', label: 'On Cuff', priceDelta: 700 },
        { value: 'chest', label: 'On Chest', priceDelta: 700 },
      ],
    },
  ],
};
