import type { MtmOptionSet } from '@/types/trouserOptions';

/**
 * Business Suit MTM option set
 * Defines customisation options for professional business suits.
 * Conforms to the shared MtmOptionSet / MtmOption schema.
 */
export const businessSuitOptionSet: MtmOptionSet = {
  id: 'suit-business-v1',
  handle: 'suit-business-v1',
  title: 'Business Suit Core v1',
  category: 'suit',
  version: 'v1',
  options: [
    {
      key: 'jacket_fit',
      label: 'Jacket Fit',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 10,
      section: 'design',
      choices: [
        { value: 'slim_fit', label: 'Slim Fit', priceDelta: 0 },
        { value: 'regular_fit', label: 'Regular Fit', priceDelta: 0 },
        { value: 'classic_fit', label: 'Classic Fit', priceDelta: 0 },
      ],
    },
    {
      key: 'jacket_style',
      label: 'Jacket Style',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 20,
      section: 'design',
      choices: [
        { value: 'two_button', label: 'Two Button', priceDelta: 0 },
        { value: 'three_button', label: 'Three Button', priceDelta: 1500 },
        { value: 'center_vent', label: 'Center Vent', priceDelta: 0 },
        { value: 'side_vents', label: 'Side Vents', priceDelta: 1000 },
      ],
    },
    {
      key: 'lapel_type',
      label: 'Lapel Type',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 30,
      section: 'design',
      choices: [
        { value: 'notch_lapel', label: 'Notch Lapel', priceDelta: 0 },
        { value: 'peak_lapel', label: 'Peak Lapel', priceDelta: 2000 },
      ],
    },
    {
      key: 'lapel_width',
      label: 'Lapel Width',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 40,
      section: 'design',
      choices: [
        { value: 'narrow', label: 'Narrow (1.75")', priceDelta: 0 },
        { value: 'standard', label: 'Standard (2.25")', priceDelta: 0 },
        { value: 'wide', label: 'Wide (2.75")', priceDelta: 0 },
      ],
    },
    {
      key: 'pocket_style',
      label: 'Pocket Style',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 50,
      section: 'pockets',
      choices: [
        { value: 'patch_pockets', label: 'Patch Pockets', priceDelta: 0 },
        { value: 'flap_pockets', label: 'Flap Pockets', priceDelta: 0 },
        { value: 'welt_pockets', label: 'Welt Pockets', priceDelta: 1000 },
      ],
    },
    {
      key: 'button_count',
      label: 'Number of Buttons',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 60,
      section: 'design',
      choices: [
        { value: 'one_button', label: 'One Button', priceDelta: 0 },
        { value: 'two_button', label: 'Two Buttons', priceDelta: 0 },
        { value: 'three_button', label: 'Three Buttons', priceDelta: 1500 },
      ],
    },
    {
      key: 'lining',
      label: 'Jacket Lining',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 70,
      section: 'construction',
      choices: [
        { value: 'full_lining', label: 'Full Lining', priceDelta: 2000 },
        { value: 'half_lining', label: 'Half Lining', priceDelta: 1000 },
        { value: 'no_lining', label: 'Unlined', priceDelta: 0 },
      ],
    },
    {
      key: 'trouser_style',
      label: 'Trouser Style',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 80,
      section: 'design',
      choices: [
        { value: 'dress_pants', label: 'Dress Pants', priceDelta: 0 },
        { value: 'chinos', label: 'Chinos', priceDelta: 0 },
        { value: 'wool_blend', label: 'Wool Blend', priceDelta: 500 },
      ],
    },
    {
      key: 'trouser_fit',
      label: 'Trouser Fit',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 90,
      section: 'design',
      choices: [
        { value: 'slim', label: 'Slim', priceDelta: 0 },
        { value: 'regular', label: 'Regular', priceDelta: 0 },
        { value: 'classic', label: 'Classic', priceDelta: 0 },
      ],
    },
    {
      key: 'button_finish',
      label: 'Button Material',
      type: 'select',
      uiHint: 'dropdown',
      required: false,
      sortOrder: 100,
      section: 'finish',
      choices: [
        { value: 'standard_buttons', label: 'Standard Buttons', priceDelta: 0 },
        { value: 'horn_buttons', label: 'Horn Buttons', priceDelta: 1000 },
        { value: 'mother_of_pearl', label: 'Mother of Pearl', priceDelta: 2500 },
      ],
    },
  ],
};

/**
 * Wedding Suit MTM option set
 * Defines customisation options for formal wedding suits with elegant details.
 */
export const weddingSuitOptionSet: MtmOptionSet = {
  id: 'suit-wedding-v1',
  handle: 'suit-wedding-v1',
  title: 'Wedding Suit Core v1',
  category: 'suit',
  version: 'v1',
  options: [
    {
      key: 'jacket_fit',
      label: 'Jacket Fit',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 10,
      section: 'design',
      choices: [
        { value: 'slim_fit', label: 'Slim Fit (Modern)', priceDelta: 0 },
        { value: 'regular_fit', label: 'Regular Fit (Classic)', priceDelta: 0 },
        { value: 'classic_fit', label: 'Classic Fit (Heritage)', priceDelta: 0 },
      ],
    },
    {
      key: 'jacket_style',
      label: 'Jacket Button Configuration',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 20,
      section: 'design',
      choices: [
        { value: 'one_button', label: 'One Button (Modern)', priceDelta: 0 },
        { value: 'two_button', label: 'Two Button (Classic)', priceDelta: 0 },
        { value: 'three_button', label: 'Three Button (Heritage)', priceDelta: 1500 },
      ],
    },
    {
      key: 'lapel_type',
      label: 'Lapel Type',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 30,
      section: 'design',
      choices: [
        { value: 'notch_lapel', label: 'Notch Lapel', priceDelta: 0 },
        { value: 'peak_lapel', label: 'Peak Lapel (Formal)', priceDelta: 3000 },
        { value: 'shawl_collar', label: 'Shawl Collar (Elegant)', priceDelta: 5000 },
      ],
    },
    {
      key: 'lapel_width',
      label: 'Lapel Width',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 40,
      section: 'design',
      choices: [
        { value: 'narrow', label: 'Narrow (1.75")', priceDelta: 0 },
        { value: 'standard', label: 'Standard (2.25")', priceDelta: 0 },
        { value: 'wide', label: 'Wide (2.75")', priceDelta: 500 },
      ],
    },
    {
      key: 'pocket_style',
      label: 'Pocket Style',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 50,
      section: 'pockets',
      choices: [
        { value: 'patch_pockets', label: 'Patch Pockets', priceDelta: 0 },
        { value: 'flap_pockets', label: 'Flap Pockets (Standard)', priceDelta: 0 },
        { value: 'welt_pockets', label: 'Welt Pockets (Formal)', priceDelta: 1500 },
        { value: 'ticket_pocket', label: 'with Ticket Pocket', priceDelta: 2000 },
      ],
    },
    {
      key: 'back_vent',
      label: 'Back Vent',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 60,
      section: 'construction',
      choices: [
        { value: 'center_vent', label: 'Center Vent (Classic)', priceDelta: 0 },
        { value: 'side_vents', label: 'Side Vents (Modern)', priceDelta: 1000 },
      ],
    },
    {
      key: 'lining',
      label: 'Jacket Lining',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 70,
      section: 'construction',
      choices: [
        { value: 'full_lining', label: 'Full Lining (Formal)', priceDelta: 3000 },
        { value: 'half_lining', label: 'Half Lining', priceDelta: 1500 },
        { value: 'no_lining', label: 'Unlined', priceDelta: 0 },
      ],
    },
    {
      key: 'sleeve_style',
      label: 'Sleeve Style',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 80,
      section: 'construction',
      choices: [
        { value: 'standard', label: 'Standard Sleeve', priceDelta: 0 },
        { value: 'functional_cuff', label: 'Functional Cuff (Formal)', priceDelta: 2000 },
      ],
    },
    {
      key: 'trouser_style',
      label: 'Trouser Style',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 90,
      section: 'design',
      choices: [
        { value: 'dress_pants', label: 'Dress Pants (Flat Front)', priceDelta: 0 },
        { value: 'dress_pants_pleated', label: 'Dress Pants (Pleated)', priceDelta: 500 },
        { value: 'wool_blend', label: 'Premium Wool Blend', priceDelta: 1000 },
      ],
    },
    {
      key: 'trouser_fit',
      label: 'Trouser Fit',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 100,
      section: 'design',
      choices: [
        { value: 'slim', label: 'Slim (Modern)', priceDelta: 0 },
        { value: 'regular', label: 'Regular (Classic)', priceDelta: 0 },
        { value: 'classic', label: 'Classic (Heritage)', priceDelta: 0 },
      ],
    },
    {
      key: 'button_finish',
      label: 'Button Material',
      type: 'select',
      uiHint: 'dropdown',
      required: true,
      sortOrder: 110,
      section: 'finish',
      choices: [
        { value: 'mother_of_pearl', label: 'Mother of Pearl (Formal)', priceDelta: 3000 },
        { value: 'horn_buttons', label: 'Horn Buttons', priceDelta: 1500 },
        { value: 'leather_buttons', label: 'Leather Buttons', priceDelta: 2000 },
        { value: 'silk_buttons', label: 'Silk-Covered Buttons (Premium)', priceDelta: 4000 },
      ],
    },
  ],
};

/**
 * Casual Suit MTM option set
 * Defines customisation options for relaxed, modern casual suits.
 */
export const casualSuitOptionSet: MtmOptionSet = {
  id: 'suit-casual-v1',
  handle: 'suit-casual-v1',
  title: 'Casual Suit Core v1',
  category: 'suit',
  version: 'v1',
  options: [
    {
      key: 'jacket_fit',
      label: 'Jacket Fit',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 10,
      section: 'design',
      choices: [
        { value: 'slim_fit', label: 'Slim Fit', priceDelta: 0 },
        { value: 'regular_fit', label: 'Regular Fit', priceDelta: 0 },
        { value: 'oversized', label: 'Oversized (Relaxed)', priceDelta: 500 },
      ],
    },
    {
      key: 'jacket_style',
      label: 'Jacket Configuration',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 20,
      section: 'design',
      choices: [
        { value: 'unstructured', label: 'Unstructured (Relaxed)', priceDelta: 0 },
        { value: 'half_structured', label: 'Half Structured', priceDelta: 1000 },
        { value: 'structured', label: 'Fully Structured', priceDelta: 500 },
      ],
    },
    {
      key: 'lapel_type',
      label: 'Lapel Type',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 30,
      section: 'design',
      choices: [
        { value: 'notch_lapel', label: 'Notch Lapel', priceDelta: 0 },
        { value: 'roman_collar', label: 'Roman Collar (Modern)', priceDelta: 1500 },
        { value: 'rolling_lapel', label: 'Rolling Lapel', priceDelta: 2000 },
      ],
    },
    {
      key: 'pocket_style',
      label: 'Pocket Style',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 40,
      section: 'pockets',
      choices: [
        { value: 'patch_pockets', label: 'Patch Pockets (Casual)', priceDelta: 0 },
        { value: 'flap_pockets', label: 'Flap Pockets', priceDelta: 500 },
        { value: 'welt_pockets', label: 'Welt Pockets (Refined)', priceDelta: 1000 },
      ],
    },
    {
      key: 'button_count',
      label: 'Jacket Buttons',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 50,
      section: 'design',
      choices: [
        { value: 'single_breasted_one', label: 'Single Breasted (One Button)', priceDelta: 0 },
        { value: 'single_breasted_two', label: 'Single Breasted (Two Button)', priceDelta: 0 },
        { value: 'double_breasted', label: 'Double Breasted', priceDelta: 2000 },
      ],
    },
    {
      key: 'sleeve_finish',
      label: 'Sleeve Finish',
      type: 'radio',
      uiHint: 'buttons',
      required: false,
      sortOrder: 60,
      section: 'construction',
      choices: [
        { value: 'standard', label: 'Standard Cuff', priceDelta: 0 },
        { value: 'rolled_edge', label: 'Rolled Edge (Modern)', priceDelta: 1000 },
        { value: 'functional_cuff', label: 'Functional Cuff', priceDelta: 1500 },
      ],
    },
    {
      key: 'lining',
      label: 'Jacket Lining',
      type: 'radio',
      uiHint: 'buttons',
      required: false,
      sortOrder: 70,
      section: 'construction',
      choices: [
        { value: 'full_lining', label: 'Full Lining', priceDelta: 1500 },
        { value: 'half_lining', label: 'Half Lining (Casual)', priceDelta: 500 },
        { value: 'no_lining', label: 'Unlined (Very Casual)', priceDelta: 0 },
      ],
    },
    {
      key: 'trouser_style',
      label: 'Trouser Style',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 80,
      section: 'design',
      choices: [
        { value: 'chinos', label: 'Chinos', priceDelta: 0 },
        { value: 'dress_pants', label: 'Dress Pants', priceDelta: 0 },
        { value: 'wool_trousers', label: 'Wool Trousers', priceDelta: 800 },
        { value: 'linen_blend', label: 'Linen Blend (Summer)', priceDelta: 600 },
      ],
    },
    {
      key: 'trouser_fit',
      label: 'Trouser Fit',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 90,
      section: 'design',
      choices: [
        { value: 'slim', label: 'Slim', priceDelta: 0 },
        { value: 'regular', label: 'Regular', priceDelta: 0 },
        { value: 'relaxed', label: 'Relaxed (Casual)', priceDelta: 0 },
        { value: 'wide_leg', label: 'Wide Leg (Trend)', priceDelta: 500 },
      ],
    },
    {
      key: 'button_finish',
      label: 'Button Style',
      type: 'select',
      uiHint: 'dropdown',
      required: false,
      sortOrder: 100,
      section: 'finish',
      choices: [
        { value: 'standard_buttons', label: 'Standard Buttons', priceDelta: 0 },
        { value: 'horn_buttons', label: 'Horn Buttons', priceDelta: 500 },
        { value: 'wooden_buttons', label: 'Wooden Buttons (Organic)', priceDelta: 1000 },
        { value: 'colored_buttons', label: 'Colored Buttons (Statement)', priceDelta: 800 },
      ],
    },
  ],
};

/**
 * Re-export all suit option sets for use in controllers
 */
export const allSuitOptionSets = {
  business: businessSuitOptionSet,
  wedding: weddingSuitOptionSet,
  casual: casualSuitOptionSet,
} as const;

export type SuitVariant = keyof typeof allSuitOptionSets;
