import type { MtmOptionSet } from '@/types/trouserOptions';

export const waistcoatOptionSet: MtmOptionSet = {
  id: 'waistcoat-core-v1',
  handle: 'waistcoat-core-v1',
  title: 'Waistcoat Core v1',
  category: 'vest',
  version: 'v1',
  options: [
    {
      key: 'fit',
      label: 'Waistcoat Fit',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 10,
      section: 'design',
      choices: [
        { value: 'slim', label: 'Slim', priceDelta: 0 },
        { value: 'tailored', label: 'Tailored', priceDelta: 0 },
        { value: 'classic', label: 'Classic', priceDelta: 0 },
      ],
    },
    {
      key: 'front_style',
      label: 'Front Style',
      type: 'radio',
      uiHint: 'cards',
      required: true,
      sortOrder: 20,
      section: 'design',
      choices: [
        { value: 'single_breasted', label: 'Single Breasted', priceDelta: 0 },
        { value: 'double_breasted', label: 'Double Breasted', priceDelta: 1500 },
      ],
    },
    {
      key: 'buttons',
      label: 'Button Count',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 30,
      section: 'design',
      choices: [
        { value: 'five', label: '5 Button', priceDelta: 0 },
        { value: 'six', label: '6 Button', priceDelta: 500 },
      ],
    },
    {
      key: 'neckline',
      label: 'Neckline',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 40,
      section: 'design',
      choices: [
        { value: 'v_neck', label: 'V-Neck', priceDelta: 0 },
        { value: 'u_neck', label: 'U-Neck', priceDelta: 600 },
        { value: 'shawl', label: 'Shawl', priceDelta: 1200 },
      ],
    },
    {
      key: 'back_material',
      label: 'Back Material',
      type: 'radio',
      uiHint: 'buttons',
      required: true,
      sortOrder: 50,
      section: 'construction',
      choices: [
        { value: 'lining', label: 'Lining', priceDelta: 0 },
        { value: 'self_fabric', label: 'Self Fabric', priceDelta: 1400 },
      ],
    },
    {
      key: 'front_pockets',
      label: 'Front Pockets',
      type: 'radio',
      uiHint: 'buttons',
      required: false,
      sortOrder: 60,
      section: 'pockets',
      choices: [
        { value: 'none', label: 'No Pockets', priceDelta: 0 },
        { value: 'welt', label: 'Welt', priceDelta: 0 },
        { value: 'ticket', label: 'Ticket', priceDelta: 700 },
      ],
    },
    {
      key: 'button_finish',
      label: 'Button Finish',
      type: 'select',
      uiHint: 'dropdown',
      required: false,
      sortOrder: 70,
      section: 'finish',
      choices: [
        { value: 'standard', label: 'Standard', priceDelta: 0 },
        { value: 'mother_of_pearl', label: 'Mother of Pearl', priceDelta: 1500 },
        { value: 'horn', label: 'Horn', priceDelta: 900 },
      ],
    },
  ],
};
